name: GitHub Readme Stats

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  workflow_dispatch: # Allows manual run

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Generate General Stats
      - name: Generate Stats Card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: stats
          options: 'username=HawkOsm&show_icons=true&theme=dark'
          path: github-stats.svg
          token: ${{ secrets.GH_TOKEN }}

      # Generate Top Languages
      - name: Generate Top Languages Card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: top-langs
          options: 'username=HawkOsm&layout=compact&theme=dark'
          path: top-langs.svg
          token: ${{ secrets.GH_TOKEN }}

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add github-stats.svg top-langs.svg
          git commit -m "Update GitHub Stats" || exit 0
          git push
